AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create Transform Layer Glue tables and GLue Crawlers.
Parameters:
  pOrganisation:
    Description: The name of the environment where resource to be deployed
    Type: String

  pBucketEnvironment:
    Description: The name of the environment for bucket name
    Type: String
    AllowedValues:
      - dev
      - tst
      - prd

  pRoleEnvironment:
    Description: The name of the environment for Glue role
    Type: String
    AllowedValues:
      - dev
      - test
      - prd
      - prod

  pEnvironment:
    Description: The name of the environment where resource to be deployed
    Type: String
    AllowedValues: 
      - dev
      - plk
      - prd

  pRegion:
    Description: The region name
    Type: String
    AllowedValues:
      - us
      - emea

  bucketRegion:
    Description: The region name
    Type: String
    AllowedValues:
      - us-east-2
      - eu-central-1

  # pRegionSpecific:
  #   Description: The region name
  #   Type: String
  #   Default: amia,claria
  #   AllowedValues:
  #     - amia,claria
  #     - amia
  #     - claria    
  pRegionSpecificAmia:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
  
  pRegionSpecificClaria:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"

  pBusinessUnit:
    Description: The business unit name
    ConstraintDescription: The name of the business should start with alphabet and in lowercase
    AllowedPattern: "[a-z][a-z0-9]*"
    Type: String

  pDataLayer:
    Type: String
    Description: Data layer names

  pSchemaId:
    Type: Number
    Description: DB instance id or ENV Name

  pTagABACAppName:
    Type: String
    Description: The name of the application you are deploying

  pTagOwnerValue:
    Type: 'String'

  pTagAppidValue:
    Description: Provide the applciaton ID
    Type: 'String'


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Tag Configuration"
        Parameters:
          - pTagAppidValue
          - pTagOwnerValue
          - pTagABACAppName

  AWS::CloudFormation::Tags:
    - Key: AppId
      Value: !Ref pTagAppidValue
    - Key: Owner
      Value: !Ref pTagOwnerValue
    - Key: ABACAppName
      Value: !Ref pTagABACAppName

Resources:          
  rRDHAnalyticsCorerenalGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: 
          Fn::Sub:
            - '${ORG}_${BU}_${LAYER}_${ENV}_${REG}c_corerenal'
            - ORG: !Ref pOrganisation
              BU: !Ref pBusinessUnit
              LAYER: !Ref pDataLayer
              ENV: !Ref pEnvironment
              REG: !Ref pSchemaId
        CreateTableDefaultPermissions:
          - 
            Permissions:
              - ALL                   
            Principal:
              DataLakePrincipalIdentifier: EVERYONE  

  rRDHTransformCorerenalGlueCrawler:
      Type: AWS::Glue::Crawler
      Properties:
        DatabaseName: !Ref rRDHAnalyticsCorerenalGlueDatabase
        Description: Glue crawler for the Core Renal Database
        Name: !Ref rRDHAnalyticsCorerenalGlueDatabase
        Role: !Sub van-${pRoleEnvironment}-entplat-${pBusinessUnit}-glue-role
        Schedule: 
          ScheduleExpression: "cron(0 0 1 * ? *)"
        SchemaChangePolicy: 
          UpdateBehavior: UPDATE_IN_DATABASE
        Targets: 
          HudiTargets:
            - Paths:
              - !Sub 
                - "s3://van-${env}-rdh-enterpriseanalytics-${region}-translate-bkt/${LAYER}/${BU}_${ENV}_${REG}/${BU}_${LAYER}_${ENV}_${REG}c_corerenal/"
                - env: !Ref pBucketEnvironment
                  region: !Ref pRegion
                  LAYER: !Ref pDataLayer
                  BU: !Ref pBusinessUnit
                  ENV: !Ref pEnvironment
                  REG: !Ref pSchemaId
                  BukREG: !Ref bucketRegion


Outputs:
  # Core Renal
  oRDHAnalyticsCorerenalGlueDatabase:
    Description: Core Renal Database Name
    Value: !Ref rRDHAnalyticsCorerenalGlueDatabase
  oRDHTransformCorerenalGlueCrawler:
    Description: Core Renal Crawler Name
    Value: !Ref rRDHTransformCorerenalGlueCrawler

